local ness_list = { "dim", "bright", "stark", "warm", "default" }

for _, ness in ipairs(ness_list) do
	local specs_name = ness ~= "default" and "specs_" .. ness or "specs"
	local specs = getfenv()[specs_name]
	if specs then
		---@diagnostic disable: undefined-global
		-- selene: allow(undefined_variable)
		run(
			{ specs, p, term },
			transform.colorscheme_to_term_colors,
			function(colors)
				return vim.tbl_extend("keep", colors, {
					name = name,
					author = "Michael Chris Lopez",
					license = "MIT",
					upstream = string.format(
						"https://github.com/mcchrish/zenbones.nvim/raw/main/extras/kitty/%s.conf",
						name
					),
					blurb = description,
					url_color = term.bright_magenta,
					tab_active_bg = specs.Search.bg,
					tab_active_fg = colors.fg,
					tab_inactive_bg = specs.StatusLine.bg,
					tab_inactive_fg = colors.fg,
				})
			end,
			contrib.kitty,
			{ prepend, "# This file is auto-generated by shipwright.nvim" },
			{ overwrite, string.format("extras/kitty/%s_%s.conf", name, ness) }
		)
		-- selene: deny(undefined_variable)
		---@diagnostic enable: undefined-global
	end
end
